Features
VolffS/quiz pull request #1
Opened 2024-03-11 07:03 UTC by VolffS

2024-03-11 08:01 UTC, xDSUP commented on src/components/menu/menu.tsx
> +import { UseQuestionsType} from "../../assets/question.ts";
по директориям. Почитай для чего нужен public, кажется сейчас он немного не так используется и картинки должны быть в assets(https://v3.vitejs.ru/guide/assets.html), а то, что лежит сейчас там можно перенести в папку data или чет подобное

2024-03-11 08:03 UTC, xDSUP commented on src/assets/question.ts
> +export const useQuestions = () => {
вынеси хук в папку hooks в отдельный файл

2024-03-11 08:03 UTC, xDSUP commented on src/assets/question.ts
> +     // Функция для удаления задачи из списка по ее ID
коммент излишен, это должно быть понятно из названия

2024-03-11 08:06 UTC, xDSUP commented on src/components/main/main.tsx
> +                ? <Quiz callback={changeIsGame} useQuiz={useQuiz}  />
хм, кажется тут будет актуален react-router и отрисовка по пути, а не такая с условием, давай его завезем и чуть переделаем

2024-03-11 08:10 UTC, xDSUP commented on src/components/quiz/quiz.tsx
> +export default function Quiz({callback, useQuiz}: Readonly<{callback:()=> void, useQuiz:UseQuestionsType }>) {
Зачем передавать весь объект, а использовать только вопросы, передавай только их. 
callback - ужасное название, вот, как я пойму, что туда передается, и что там происходит?

2024-03-11 08:13 UTC, xDSUP commented on src/components/answer/answer.tsx
> +            {answers.map(answer => <AnswerButton key={(Math.random()*1e8).toString(16)}
прикольно, key завозили, чтобы было меньше перерисовок, а у тебя с каждым ререндером будет новый)

2024-03-11 08:13 UTC, xDSUP commented on src/components/answer/answer.tsx
> +export default function Answer({answers, callback}: Readonly<{answers: Array<string>, callback: (answer: string) => void }>) {
опять callback какой-то

2024-03-11 08:17 UTC, xDSUP commented on src/components/button/btn.tsx
> +export function Btn({text, callback}: Readonly<{ text: string|number, callback: (ev: any) => void }>) {
callback_

2024-03-11 08:21 UTC, xDSUP commented on src/components/input/input.tsx
> +                   : inputText ?? text} onChange={handlerChange} required/>
а чего это за констукции

2024-03-11 08:26 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +                <Btn text={"Отменить Всё"} callback={canselModify}/>
cancel

2024-03-11 08:26 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +    function typ() {
кто такой "туп"

2024-03-11 08:27 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +        const question :any = {
тут то ты тип знаешь

2024-03-11 08:33 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +    function modifyQuiz(form: any) {
React.FormEvent<HTMLFormElement>

2024-03-11 08:35 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +                    : useQuiz.questions.map((value, index) => <Btn
форматирование...

2024-03-11 08:55 UTC, xDSUP requested changes

2024-03-11 08:55 UTC, xDSUP commented on src/assets/question.ts
> +         answers: ["Да","Нет"]
форма создания всегда ждет 4 ответов, а тут 2. Почему пользователя обделяют?

2024-03-11 08:55 UTC, xDSUP commented on src/assets/question.ts
> +    answers: Array<string>;
я бы докинул айдишник ответам. и как правильный хранил именно бы айди, их сравнивать быстрее будет + всякие рандомы в key прописывать не придется

2024-03-11 08:55 UTC, xDSUP commented on src/components/question/question.tsx
> +                <Answer answers={shuffle(question.answers)}
вроде по названию это ответ, а принимает при этом массив ответов.... 

AnswerList тогда уж

2024-03-11 08:55 UTC, xDSUP commented on src/components/answer/answer.tsx
> +        <div className="quiz__container__answer">
семантика < li/> < ul/> для списков мб?

2024-03-11 08:55 UTC, xDSUP commented on src/components/statisticsPlayer/statisticsPlayer.tsx
> +    console.log(gifResult)
лишнее

2024-03-11 08:55 UTC, xDSUP commented on src/components/statisticsPlayer/statisticsPlayer.tsx
> +            return shuffle(gifResult.goodResult)[0]
ты сначала перемешиваешь массив, а зачем достаешь первый, чтобы просто получить рандом? - не надо так, лишняя работа бедному браузеру)

Тут лучше взять рандомное число от 0 до конца массива, что будет рандомным индексом, а значит и ранд элементом)

2024-03-11 08:55 UTC, xDSUP commented on src/components/textarea/textarea.tsx
> +    const [inputText, setInputText] = useState({text: undefined, id: id});
id не меняется, чего ему делать в стейте?

2024-03-11 08:55 UTC, xDSUP commented on src/components/modify-quiz/change-question.tsx
> +                   style={{display: "none"}} readOnly={true}/>
можно просто readOnly без скобок

2024-03-11 08:55 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +                <Btn text={"Завершить"} callback={completionModify}/>
не сохраняет изменения

2024-03-11 08:55 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +                {isAddQuestion ?"" : <BtnSubmit text="Удалить" callback={() => {action = "delete"}}/>}
если я что-то добавляю, то крашится при удалении последнего элемента или после добавлнеия нового.

2024-03-11 08:55 UTC, xDSUP commented on src/components/modify-quiz/modify-quiz.tsx
> +                    : <BtnSubmit text={"Изменить"} callback={() => {action = "update"}}/>}
на кнопках очень не хватает стиля при клике, порой непонятно: нажал я или нет

2024-03-12 13:07 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +                    : <BtnSubmit text={"Изменить"} callback={() => {action = "update"}}/>}
done

2024-03-12 13:07 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +                {isAddQuestion ?"" : <BtnSubmit text="Удалить" callback={() => {action = "delete"}}/>}
done

2024-03-12 13:08 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +                <Btn text={"Завершить"} callback={completionModify}/>
Изменения сохраняться при нажатии кнопок "Изменить", "Добавить", "Удалить",

2024-03-12 13:08 UTC, VolffS commented on src/components/modify-quiz/change-question.tsx
> +                   style={{display: "none"}} readOnly={true}/>
Done

2024-03-12 13:08 UTC, VolffS commented on src/components/textarea/textarea.tsx
> +    const [inputText, setInputText] = useState({text: undefined, id: id});
done

2024-03-12 13:08 UTC, VolffS commented on src/components/statisticsPlayer/statisticsPlayer.tsx
> +    console.log(gifResult)
done

2024-03-12 13:09 UTC, VolffS commented on src/components/answer/answer.tsx
> +        <div className="quiz__container__answer">
В этом нет нужды

2024-03-12 13:09 UTC, VolffS commented on src/components/question/question.tsx
> +                <Answer answers={shuffle(question.answers)}
Done

2024-03-12 13:10 UTC, VolffS commented on src/assets/question.ts
> +         answers: ["Да","Нет"]
Это тестовый вопрос для проверки работоспособности и стилей проекта

2024-03-12 13:10 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +                    : useQuiz.questions.map((value, index) => <Btn
Done

2024-03-12 13:10 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +    function modifyQuiz(form: any) {
Done

2024-03-12 13:10 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +        const question :any = {
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +    function typ() {
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/modify-quiz/modify-quiz.tsx
> +                <Btn text={"Отменить Всё"} callback={canselModify}/>
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/input/input.tsx
> +                   : inputText ?? text} onChange={handlerChange} required/>
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/button/btn.tsx
> +export function Btn({text, callback}: Readonly<{ text: string|number, callback: (ev: any) => void }>) {
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/answer/answer.tsx
> +export default function Answer({answers, callback}: Readonly<{answers: Array<string>, callback: (answer: string) => void }>) {
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/answer/answer.tsx
> +            {answers.map(answer => <AnswerButton key={(Math.random()*1e8).toString(16)}
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/quiz/quiz.tsx
> +export default function Quiz({callback, useQuiz}: Readonly<{callback:()=> void, useQuiz:UseQuestionsType }>) {
Done

2024-03-12 13:11 UTC, VolffS commented on src/components/main/main.tsx
> +                ? <Quiz callback={changeIsGame} useQuiz={useQuiz}  />
Done

2024-03-12 13:11 UTC, VolffS commented on src/assets/question.ts
> +     // Функция для удаления задачи из списка по ее ID
Done

2024-03-12 13:12 UTC, VolffS commented on src/assets/question.ts
> +export const useQuestions = () => {
Done

2024-03-12 13:15 UTC, VolffS commented on src/assets/question.ts
> +    answers: Array<string>;
В этом проекте нет нужды в добавлении отдельного Id для каждого вопроса

2024-03-12 15:56 UTC, VolffS commented on src/components/menu/menu.tsx
> +import { UseQuestionsType} from "../../assets/question.ts";
done

2024-03-14 17:16 UTC, merged